repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.6
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.9
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
